version: '3'

# To start: 
# - docker-compose up
# To finish:
# - docker stop $(docker ps -a -q)
# - docker rm $(docker ps -a -q) && docker volume prune -f

services:

  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: dartydb
      POSTGRES_USER: technotilt
      POSTGRES_PASSWORD: love # How to hide properly?
    ports:
      - 5432:5432
    volumes:
      - ./_sql/:/docker-entrypoint-initdb.d
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
