version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:

  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: "darty"
      POSTGRES_USER: "technotilt"
      POSTGRES_PASSWORD: "love"
    ports:
      - 5432:5432
    volumes:
      - './sql/:/docker-entrypoint-initdb.d'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
